name: Main FTP Deployment on push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: /dist/

      - name: Sync file to the Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_MAIN_SERVER }}
          username: ${{ secrets.FTP_MAIN_USER }}
          password: ${{ secrets.FTP_PW }}
